# Generated by Django 3.1.6 on 2021-02-17 22:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(editable=False)),
                ('updated_at', models.DateTimeField()),
                ('liked', models.ManyToManyField(blank=True, related_name='liked_dashboards', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Panel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('panel_type', models.CharField(choices=[('', 'Select a type of panel'), ('pie', 'Pie-panel of languages used in repo'), ('bar', 'Bar-panel of languages used in repo'), ('all', 'All repos for the user'), ('star', 'All starred repos for the user')], max_length=16)),
                ('user_name', models.CharField(max_length=127)),
                ('repo_name', models.CharField(blank=True, max_length=127)),
                ('size', models.CharField(choices=[('', 'Select a size'), ('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], max_length=16)),
                ('created_at', models.DateTimeField(editable=False)),
                ('updated_at', models.DateTimeField()),
                ('dashboards', models.ManyToManyField(blank=True, related_name='panels', to='core.Dashboard')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
